# NUMPY

In [16]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.shape

(3, 5)

In [17]:
a.ndim

2

In [19]:
a.dtype.name

'int32'

In [20]:
a.itemsize

4

In [21]:
a.size

15

In [22]:
type(a)

numpy.ndarray

In [24]:
b = ([6, 7, 8])
type(b)

list

In [25]:
c = (6, 7, 8)
type(c)

tuple

In [26]:
b

[6, 7, 8]

# Array Creation

In [28]:
a = np.array([2, 3, 4])
a



array([2, 3, 4])

In [29]:
a.dtype

dtype('int32')

In [31]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [34]:
b = np.array([(1, 2), (3, 4)])
b

array([[1, 2],
       [3, 4]])

In [35]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [36]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [38]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [43]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a = np.ones((2, 3, 4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
a = np.empty((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

## Crear secuencias de números

In [49]:
a = np.arange(10,30,5)
a

array([10, 15, 20, 25])

In [50]:
a = np.arange(10,40,5)
a

array([10, 15, 20, 25, 30, 35])

In [51]:
a = np.arange(10,30,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### Repaso

In [2]:
import numpy as np
a = np.array ([2, 3, 4])
a


dtype('int32')

In [3]:
a.dtype

dtype('int32')

In [6]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [7]:
b.dtype

dtype('float64')

In [8]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
c = np.array([[1, 2],[3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
e = np.ones((2, 3, 4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
f = np.ones((1, 3))
f

array([[1., 1., 1.]])

In [27]:
g = np.ones((2, 3, 3, 4))
g

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

## 1 - 1D array creation functions

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = np.arange(2, 10, dtype=float)
b

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
c = np.arange(2, 3, 0.1)
c

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [34]:
d = np.linspace(1., 4., 6)
d

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

## 2 - 2D array creation functions

In [35]:
a = np.eye(3)  # Matriz identidad
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
b = np.eye(3, 5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
a = np.diag([1, 2, 3])  # Matriz diagonal
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
b = np.diag([1, 2, 3], 1)
b

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [41]:
c = np.array([[1, 2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [42]:
np.diag(c)

array([1, 4])

### Replicating, joining, or mutating existing arrays

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [46]:
a # en este ejemplo creamos a "b" como una vista de "a"

array([2, 3, 3, 4, 5, 6])

# numpy.copy

In [47]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a =', a, '; b =', b)

a = [1 2 3 4] ; b = [2 3]


# Repaso

In [4]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
c = np.arange(15).reshape(5,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
d = np.arange(15).reshape(15)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [16]:
list_1 = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
list_1

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [17]:
a = np.array(list_1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Diccionarios

In [26]:
dic ={'Pablo':44, 'Diego':43, 'Marina':37, 'Nerea':33}
print(dic)

{'Pablo': 44, 'Diego': 43, 'Marina': 37, 'Nerea': 33}


In [29]:
dic ['Sandra'] = 46
dic ['Karina'] = 50


In [30]:
print(dic)

{'Pablo': 44, 'Diego': 43, 'Marina': 37, 'Nerea': 33, 'Sandra': 46, 'Karina': 50}


In [31]:
del dic['Diego']

In [32]:
print(dic)

{'Pablo': 44, 'Marina': 37, 'Nerea': 33, 'Sandra': 46, 'Karina': 50}


# Listas

In [34]:
a = [1, 2, 3, 4, 5]

In [35]:
b = a[:]

In [36]:
b

[1, 2, 3, 4, 5]

In [37]:
b[0] = 44
b

[44, 2, 3, 4, 5]

In [38]:
a

[1, 2, 3, 4, 5]

In [40]:
c = a[:2]
c

[1, 2]

In [41]:
d = a[1:-1]

In [42]:
d

[2, 3, 4]

In [43]:
a

[1, 2, 3, 4, 5]

In [44]:
d = a[0:4]
d

[1, 2, 3, 4]

In [45]:
d = a[0:5]
d

[1, 2, 3, 4, 5]

In [46]:
d = a[1:5]
d

[2, 3, 4, 5]

In [47]:
d = a[1:4]
d

[2, 3, 4]

# Tuplas

In [48]:
a = 1, 2, 3, 4

In [50]:
a(0) = 44  # las tuplas no se pueden modificar

SyntaxError: cannot assign to function call (<ipython-input-50-a669a8908ec3>, line 1)

In [51]:
a

(1, 2, 3, 4)

In [53]:
a = 1, 2, 3, 4
b = (5, 6, 7, 8)
print(a)
print(b)

(1, 2, 3, 4)
(5, 6, 7, 8)


In [54]:
print(a[0])

1


# Array Creation

In [55]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [56]:
np.random.choice([0,1],500,p=[0.3,0.7])

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [57]:
np.random.choice([0,1],500,p=[0.3,0.7])

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,

In [58]:
np.random.normal(1, 2, 100)

array([-0.6659958 ,  0.62398394,  1.0674748 , -0.21730777,  1.14528278,
       -0.1882814 ,  0.86255359,  2.65866574, -0.31050735,  1.88478489,
        2.44442194,  0.50182545,  3.98771408,  0.29462438,  1.26700136,
        1.53730021,  3.06911103,  0.9333691 ,  0.04560098,  1.91589478,
        0.1746384 ,  0.77388468,  2.93425507, -2.50908324, -1.84646917,
        2.95482024, -0.13317341,  1.84598758,  1.87679011,  0.21783479,
       -0.30800843, -2.39962531,  4.46541272,  0.29586638,  1.35852135,
        1.14024482,  1.93638913,  2.66245492, -2.96807779,  4.16432188,
       -0.88951825,  2.96140172,  2.3464236 , -0.76316935, -1.48772797,
        0.38242439,  0.24488342,  8.23927669,  0.46535812,  1.03476288,
        1.82469598,  0.38846721, -0.77138647, -0.80870273,  1.70446194,
       -0.74598356,  0.74265603,  1.81955741,  1.43054006, -2.2187002 ,
       -1.71084857,  0.25618137,  1.55751323,  1.53620225,  0.7191229 ,
       -1.33873951,  2.63921959,  1.76528139,  3.59136964,  3.38